// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package configs.proxies;

public class ConfigGroup
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject configGroupMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Configs.ConfigGroup";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		GroupName("GroupName"),
		IsValid("IsValid"),
		ConfigGroup_ConfigProduct("Configs.ConfigGroup_ConfigProduct");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ConfigGroup(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ConfigGroup(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configGroupMendixObject)
	{
		if (configGroupMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, configGroupMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.configGroupMendixObject = configGroupMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ConfigGroup.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static configs.proxies.ConfigGroup initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return configs.proxies.ConfigGroup.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static configs.proxies.ConfigGroup initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new configs.proxies.ConfigGroup(context, mendixObject);
	}

	public static configs.proxies.ConfigGroup load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return configs.proxies.ConfigGroup.initialize(context, mendixObject);
	}

	public static java.util.List<configs.proxies.ConfigGroup> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> configs.proxies.ConfigGroup.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of GroupName
	 */
	public final java.lang.String getGroupName()
	{
		return getGroupName(getContext());
	}

	/**
	 * @param context
	 * @return value of GroupName
	 */
	public final java.lang.String getGroupName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GroupName.toString());
	}

	/**
	 * Set value of GroupName
	 * @param groupname
	 */
	public final void setGroupName(java.lang.String groupname)
	{
		setGroupName(getContext(), groupname);
	}

	/**
	 * Set value of GroupName
	 * @param context
	 * @param groupname
	 */
	public final void setGroupName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String groupname)
	{
		getMendixObject().setValue(context, MemberNames.GroupName.toString(), groupname);
	}

	/**
	 * @return value of IsValid
	 */
	public final java.lang.Boolean getIsValid()
	{
		return getIsValid(getContext());
	}

	/**
	 * @param context
	 * @return value of IsValid
	 */
	public final java.lang.Boolean getIsValid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsValid.toString());
	}

	/**
	 * Set value of IsValid
	 * @param isvalid
	 */
	public final void setIsValid(java.lang.Boolean isvalid)
	{
		setIsValid(getContext(), isvalid);
	}

	/**
	 * Set value of IsValid
	 * @param context
	 * @param isvalid
	 */
	public final void setIsValid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isvalid)
	{
		getMendixObject().setValue(context, MemberNames.IsValid.toString(), isvalid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ConfigGroup_ConfigProduct
	 */
	public final configs.proxies.ConfigProduct getConfigGroup_ConfigProduct() throws com.mendix.core.CoreException
	{
		return getConfigGroup_ConfigProduct(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfigGroup_ConfigProduct
	 * @throws com.mendix.core.CoreException
	 */
	public final configs.proxies.ConfigProduct getConfigGroup_ConfigProduct(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		configs.proxies.ConfigProduct result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ConfigGroup_ConfigProduct.toString());
		if (identifier != null) {
			result = configs.proxies.ConfigProduct.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ConfigGroup_ConfigProduct
	 * @param configgroup_configproduct
	 */
	public final void setConfigGroup_ConfigProduct(configs.proxies.ConfigProduct configgroup_configproduct)
	{
		setConfigGroup_ConfigProduct(getContext(), configgroup_configproduct);
	}

	/**
	 * Set value of ConfigGroup_ConfigProduct
	 * @param context
	 * @param configgroup_configproduct
	 */
	public final void setConfigGroup_ConfigProduct(com.mendix.systemwideinterfaces.core.IContext context, configs.proxies.ConfigProduct configgroup_configproduct)
	{
		if (configgroup_configproduct == null) {
			getMendixObject().setValue(context, MemberNames.ConfigGroup_ConfigProduct.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ConfigGroup_ConfigProduct.toString(), configgroup_configproduct.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return configGroupMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final configs.proxies.ConfigGroup that = (configs.proxies.ConfigGroup) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
