// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package order.proxies;

public class ActionRecord
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject actionRecordMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Order.ActionRecord";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ActionTime("ActionTime"),
		ActionType("ActionType"),
		ActionUser("ActionUser"),
		ActionComment("ActionComment"),
		OperatePage("OperatePage"),
		ActionRecord_Order("Order.ActionRecord_Order");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ActionRecord(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ActionRecord(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject actionRecordMendixObject)
	{
		if (actionRecordMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, actionRecordMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.actionRecordMendixObject = actionRecordMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ActionRecord.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static order.proxies.ActionRecord initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return order.proxies.ActionRecord.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static order.proxies.ActionRecord initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new order.proxies.ActionRecord(context, mendixObject);
	}

	public static order.proxies.ActionRecord load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return order.proxies.ActionRecord.initialize(context, mendixObject);
	}

	public static java.util.List<order.proxies.ActionRecord> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> order.proxies.ActionRecord.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ActionTime
	 */
	public final java.util.Date getActionTime()
	{
		return getActionTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionTime
	 */
	public final java.util.Date getActionTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ActionTime.toString());
	}

	/**
	 * Set value of ActionTime
	 * @param actiontime
	 */
	public final void setActionTime(java.util.Date actiontime)
	{
		setActionTime(getContext(), actiontime);
	}

	/**
	 * Set value of ActionTime
	 * @param context
	 * @param actiontime
	 */
	public final void setActionTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date actiontime)
	{
		getMendixObject().setValue(context, MemberNames.ActionTime.toString(), actiontime);
	}

	/**
	 * Set value of ActionType
	 * @param actiontype
	 */
	public final execute.proxies.ENUM_ActionType getActionType()
	{
		return getActionType(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionType
	 */
	public final execute.proxies.ENUM_ActionType getActionType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ActionType.toString());
		if (obj == null) {
			return null;
		}
		return execute.proxies.ENUM_ActionType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ActionType
	 * @param actiontype
	 */
	public final void setActionType(execute.proxies.ENUM_ActionType actiontype)
	{
		setActionType(getContext(), actiontype);
	}

	/**
	 * Set value of ActionType
	 * @param context
	 * @param actiontype
	 */
	public final void setActionType(com.mendix.systemwideinterfaces.core.IContext context, execute.proxies.ENUM_ActionType actiontype)
	{
		if (actiontype != null) {
			getMendixObject().setValue(context, MemberNames.ActionType.toString(), actiontype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ActionType.toString(), null);
		}
	}

	/**
	 * @return value of ActionUser
	 */
	public final java.lang.String getActionUser()
	{
		return getActionUser(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionUser
	 */
	public final java.lang.String getActionUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ActionUser.toString());
	}

	/**
	 * Set value of ActionUser
	 * @param actionuser
	 */
	public final void setActionUser(java.lang.String actionuser)
	{
		setActionUser(getContext(), actionuser);
	}

	/**
	 * Set value of ActionUser
	 * @param context
	 * @param actionuser
	 */
	public final void setActionUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String actionuser)
	{
		getMendixObject().setValue(context, MemberNames.ActionUser.toString(), actionuser);
	}

	/**
	 * @return value of ActionComment
	 */
	public final java.lang.String getActionComment()
	{
		return getActionComment(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionComment
	 */
	public final java.lang.String getActionComment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ActionComment.toString());
	}

	/**
	 * Set value of ActionComment
	 * @param actioncomment
	 */
	public final void setActionComment(java.lang.String actioncomment)
	{
		setActionComment(getContext(), actioncomment);
	}

	/**
	 * Set value of ActionComment
	 * @param context
	 * @param actioncomment
	 */
	public final void setActionComment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String actioncomment)
	{
		getMendixObject().setValue(context, MemberNames.ActionComment.toString(), actioncomment);
	}

	/**
	 * Set value of OperatePage
	 * @param operatepage
	 */
	public final execute.proxies.ENUM_StateOperate_Page getOperatePage()
	{
		return getOperatePage(getContext());
	}

	/**
	 * @param context
	 * @return value of OperatePage
	 */
	public final execute.proxies.ENUM_StateOperate_Page getOperatePage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.OperatePage.toString());
		if (obj == null) {
			return null;
		}
		return execute.proxies.ENUM_StateOperate_Page.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of OperatePage
	 * @param operatepage
	 */
	public final void setOperatePage(execute.proxies.ENUM_StateOperate_Page operatepage)
	{
		setOperatePage(getContext(), operatepage);
	}

	/**
	 * Set value of OperatePage
	 * @param context
	 * @param operatepage
	 */
	public final void setOperatePage(com.mendix.systemwideinterfaces.core.IContext context, execute.proxies.ENUM_StateOperate_Page operatepage)
	{
		if (operatepage != null) {
			getMendixObject().setValue(context, MemberNames.OperatePage.toString(), operatepage.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.OperatePage.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ActionRecord_Order
	 */
	public final order.proxies.Order getActionRecord_Order() throws com.mendix.core.CoreException
	{
		return getActionRecord_Order(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionRecord_Order
	 * @throws com.mendix.core.CoreException
	 */
	public final order.proxies.Order getActionRecord_Order(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		order.proxies.Order result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ActionRecord_Order.toString());
		if (identifier != null) {
			result = order.proxies.Order.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ActionRecord_Order
	 * @param actionrecord_order
	 */
	public final void setActionRecord_Order(order.proxies.Order actionrecord_order)
	{
		setActionRecord_Order(getContext(), actionrecord_order);
	}

	/**
	 * Set value of ActionRecord_Order
	 * @param context
	 * @param actionrecord_order
	 */
	public final void setActionRecord_Order(com.mendix.systemwideinterfaces.core.IContext context, order.proxies.Order actionrecord_order)
	{
		if (actionrecord_order == null) {
			getMendixObject().setValue(context, MemberNames.ActionRecord_Order.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ActionRecord_Order.toString(), actionrecord_order.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return actionRecordMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final order.proxies.ActionRecord that = (order.proxies.ActionRecord) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
