// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package order.proxies;

public class Order
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject orderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Order.Order";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OrderNumber("OrderNumber"),
		Plant("Plant"),
		OrderType("OrderType"),
		BaseQuantity("BaseQuantity"),
		MaterialNumber("MaterialNumber"),
		MaterialDesc("MaterialDesc"),
		WBSElement("WBSElement"),
		ActualReleaseDate("ActualReleaseDate"),
		ScheduledReleaseDate("ScheduledReleaseDate"),
		ScheduledFinishDate("ScheduledFinishDate"),
		ActualStartDate("ActualStartDate"),
		Status("Status"),
		Priority("Priority"),
		Order_OrderProcess("Order.Order_OrderProcess"),
		Order_ConfigProduct("Order.Order_ConfigProduct"),
		Order_ConfigGroup("Order.Order_ConfigGroup"),
		Order_ConfigVariant("Order.Order_ConfigVariant"),
		Order_ExcelDoc("Order.Order_ExcelDoc");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Order(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Order(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject orderMendixObject)
	{
		if (orderMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, orderMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.orderMendixObject = orderMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Order.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static order.proxies.Order initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return order.proxies.Order.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static order.proxies.Order initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new order.proxies.Order(context, mendixObject);
	}

	public static order.proxies.Order load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return order.proxies.Order.initialize(context, mendixObject);
	}

	public static java.util.List<order.proxies.Order> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> order.proxies.Order.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of OrderNumber
	 */
	public final java.lang.String getOrderNumber()
	{
		return getOrderNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderNumber
	 */
	public final java.lang.String getOrderNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrderNumber.toString());
	}

	/**
	 * Set value of OrderNumber
	 * @param ordernumber
	 */
	public final void setOrderNumber(java.lang.String ordernumber)
	{
		setOrderNumber(getContext(), ordernumber);
	}

	/**
	 * Set value of OrderNumber
	 * @param context
	 * @param ordernumber
	 */
	public final void setOrderNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ordernumber)
	{
		getMendixObject().setValue(context, MemberNames.OrderNumber.toString(), ordernumber);
	}

	/**
	 * @return value of Plant
	 */
	public final java.lang.String getPlant()
	{
		return getPlant(getContext());
	}

	/**
	 * @param context
	 * @return value of Plant
	 */
	public final java.lang.String getPlant(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Plant.toString());
	}

	/**
	 * Set value of Plant
	 * @param plant
	 */
	public final void setPlant(java.lang.String plant)
	{
		setPlant(getContext(), plant);
	}

	/**
	 * Set value of Plant
	 * @param context
	 * @param plant
	 */
	public final void setPlant(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String plant)
	{
		getMendixObject().setValue(context, MemberNames.Plant.toString(), plant);
	}

	/**
	 * @return value of OrderType
	 */
	public final java.lang.String getOrderType()
	{
		return getOrderType(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderType
	 */
	public final java.lang.String getOrderType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrderType.toString());
	}

	/**
	 * Set value of OrderType
	 * @param ordertype
	 */
	public final void setOrderType(java.lang.String ordertype)
	{
		setOrderType(getContext(), ordertype);
	}

	/**
	 * Set value of OrderType
	 * @param context
	 * @param ordertype
	 */
	public final void setOrderType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ordertype)
	{
		getMendixObject().setValue(context, MemberNames.OrderType.toString(), ordertype);
	}

	/**
	 * @return value of BaseQuantity
	 */
	public final java.lang.String getBaseQuantity()
	{
		return getBaseQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of BaseQuantity
	 */
	public final java.lang.String getBaseQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BaseQuantity.toString());
	}

	/**
	 * Set value of BaseQuantity
	 * @param basequantity
	 */
	public final void setBaseQuantity(java.lang.String basequantity)
	{
		setBaseQuantity(getContext(), basequantity);
	}

	/**
	 * Set value of BaseQuantity
	 * @param context
	 * @param basequantity
	 */
	public final void setBaseQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String basequantity)
	{
		getMendixObject().setValue(context, MemberNames.BaseQuantity.toString(), basequantity);
	}

	/**
	 * @return value of MaterialNumber
	 */
	public final java.lang.String getMaterialNumber()
	{
		return getMaterialNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialNumber
	 */
	public final java.lang.String getMaterialNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialNumber.toString());
	}

	/**
	 * Set value of MaterialNumber
	 * @param materialnumber
	 */
	public final void setMaterialNumber(java.lang.String materialnumber)
	{
		setMaterialNumber(getContext(), materialnumber);
	}

	/**
	 * Set value of MaterialNumber
	 * @param context
	 * @param materialnumber
	 */
	public final void setMaterialNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialnumber)
	{
		getMendixObject().setValue(context, MemberNames.MaterialNumber.toString(), materialnumber);
	}

	/**
	 * @return value of MaterialDesc
	 */
	public final java.lang.String getMaterialDesc()
	{
		return getMaterialDesc(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialDesc
	 */
	public final java.lang.String getMaterialDesc(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialDesc.toString());
	}

	/**
	 * Set value of MaterialDesc
	 * @param materialdesc
	 */
	public final void setMaterialDesc(java.lang.String materialdesc)
	{
		setMaterialDesc(getContext(), materialdesc);
	}

	/**
	 * Set value of MaterialDesc
	 * @param context
	 * @param materialdesc
	 */
	public final void setMaterialDesc(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialdesc)
	{
		getMendixObject().setValue(context, MemberNames.MaterialDesc.toString(), materialdesc);
	}

	/**
	 * @return value of WBSElement
	 */
	public final java.lang.String getWBSElement()
	{
		return getWBSElement(getContext());
	}

	/**
	 * @param context
	 * @return value of WBSElement
	 */
	public final java.lang.String getWBSElement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WBSElement.toString());
	}

	/**
	 * Set value of WBSElement
	 * @param wbselement
	 */
	public final void setWBSElement(java.lang.String wbselement)
	{
		setWBSElement(getContext(), wbselement);
	}

	/**
	 * Set value of WBSElement
	 * @param context
	 * @param wbselement
	 */
	public final void setWBSElement(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String wbselement)
	{
		getMendixObject().setValue(context, MemberNames.WBSElement.toString(), wbselement);
	}

	/**
	 * @return value of ActualReleaseDate
	 */
	public final java.util.Date getActualReleaseDate()
	{
		return getActualReleaseDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ActualReleaseDate
	 */
	public final java.util.Date getActualReleaseDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ActualReleaseDate.toString());
	}

	/**
	 * Set value of ActualReleaseDate
	 * @param actualreleasedate
	 */
	public final void setActualReleaseDate(java.util.Date actualreleasedate)
	{
		setActualReleaseDate(getContext(), actualreleasedate);
	}

	/**
	 * Set value of ActualReleaseDate
	 * @param context
	 * @param actualreleasedate
	 */
	public final void setActualReleaseDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date actualreleasedate)
	{
		getMendixObject().setValue(context, MemberNames.ActualReleaseDate.toString(), actualreleasedate);
	}

	/**
	 * @return value of ScheduledReleaseDate
	 */
	public final java.util.Date getScheduledReleaseDate()
	{
		return getScheduledReleaseDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ScheduledReleaseDate
	 */
	public final java.util.Date getScheduledReleaseDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ScheduledReleaseDate.toString());
	}

	/**
	 * Set value of ScheduledReleaseDate
	 * @param scheduledreleasedate
	 */
	public final void setScheduledReleaseDate(java.util.Date scheduledreleasedate)
	{
		setScheduledReleaseDate(getContext(), scheduledreleasedate);
	}

	/**
	 * Set value of ScheduledReleaseDate
	 * @param context
	 * @param scheduledreleasedate
	 */
	public final void setScheduledReleaseDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date scheduledreleasedate)
	{
		getMendixObject().setValue(context, MemberNames.ScheduledReleaseDate.toString(), scheduledreleasedate);
	}

	/**
	 * @return value of ScheduledFinishDate
	 */
	public final java.util.Date getScheduledFinishDate()
	{
		return getScheduledFinishDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ScheduledFinishDate
	 */
	public final java.util.Date getScheduledFinishDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ScheduledFinishDate.toString());
	}

	/**
	 * Set value of ScheduledFinishDate
	 * @param scheduledfinishdate
	 */
	public final void setScheduledFinishDate(java.util.Date scheduledfinishdate)
	{
		setScheduledFinishDate(getContext(), scheduledfinishdate);
	}

	/**
	 * Set value of ScheduledFinishDate
	 * @param context
	 * @param scheduledfinishdate
	 */
	public final void setScheduledFinishDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date scheduledfinishdate)
	{
		getMendixObject().setValue(context, MemberNames.ScheduledFinishDate.toString(), scheduledfinishdate);
	}

	/**
	 * @return value of ActualStartDate
	 */
	public final java.util.Date getActualStartDate()
	{
		return getActualStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ActualStartDate
	 */
	public final java.util.Date getActualStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ActualStartDate.toString());
	}

	/**
	 * Set value of ActualStartDate
	 * @param actualstartdate
	 */
	public final void setActualStartDate(java.util.Date actualstartdate)
	{
		setActualStartDate(getContext(), actualstartdate);
	}

	/**
	 * Set value of ActualStartDate
	 * @param context
	 * @param actualstartdate
	 */
	public final void setActualStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date actualstartdate)
	{
		getMendixObject().setValue(context, MemberNames.ActualStartDate.toString(), actualstartdate);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final order.proxies.ENUM_OrderStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final order.proxies.ENUM_OrderStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return order.proxies.ENUM_OrderStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(order.proxies.ENUM_OrderStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, order.proxies.ENUM_OrderStatus status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * Set value of Priority
	 * @param priority
	 */
	public final order.proxies.ENUM_OrderPriority getPriority()
	{
		return getPriority(getContext());
	}

	/**
	 * @param context
	 * @return value of Priority
	 */
	public final order.proxies.ENUM_OrderPriority getPriority(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Priority.toString());
		if (obj == null) {
			return null;
		}
		return order.proxies.ENUM_OrderPriority.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Priority
	 * @param priority
	 */
	public final void setPriority(order.proxies.ENUM_OrderPriority priority)
	{
		setPriority(getContext(), priority);
	}

	/**
	 * Set value of Priority
	 * @param context
	 * @param priority
	 */
	public final void setPriority(com.mendix.systemwideinterfaces.core.IContext context, order.proxies.ENUM_OrderPriority priority)
	{
		if (priority != null) {
			getMendixObject().setValue(context, MemberNames.Priority.toString(), priority.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Priority.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Order_OrderProcess
	 */
	public final java.util.List<order.proxies.OrderProcess> getOrder_OrderProcess() throws com.mendix.core.CoreException
	{
		return getOrder_OrderProcess(getContext());
	}

	/**
	 * @param context
	 * @return value of Order_OrderProcess
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<order.proxies.OrderProcess> getOrder_OrderProcess(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<order.proxies.OrderProcess> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Order_OrderProcess.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(order.proxies.OrderProcess.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Order_OrderProcess
	 * @param order_orderprocess
	 */
	public final void setOrder_OrderProcess(java.util.List<order.proxies.OrderProcess> order_orderprocess)
	{
		setOrder_OrderProcess(getContext(), order_orderprocess);
	}

	/**
	 * Set value of Order_OrderProcess
	 * @param context
	 * @param order_orderprocess
	 */
	public final void setOrder_OrderProcess(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<order.proxies.OrderProcess> order_orderprocess)
	{
		var identifiers = order_orderprocess
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Order_OrderProcess.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Order_ConfigProduct
	 */
	public final configs.proxies.ConfigProduct getOrder_ConfigProduct() throws com.mendix.core.CoreException
	{
		return getOrder_ConfigProduct(getContext());
	}

	/**
	 * @param context
	 * @return value of Order_ConfigProduct
	 * @throws com.mendix.core.CoreException
	 */
	public final configs.proxies.ConfigProduct getOrder_ConfigProduct(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		configs.proxies.ConfigProduct result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Order_ConfigProduct.toString());
		if (identifier != null) {
			result = configs.proxies.ConfigProduct.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Order_ConfigProduct
	 * @param order_configproduct
	 */
	public final void setOrder_ConfigProduct(configs.proxies.ConfigProduct order_configproduct)
	{
		setOrder_ConfigProduct(getContext(), order_configproduct);
	}

	/**
	 * Set value of Order_ConfigProduct
	 * @param context
	 * @param order_configproduct
	 */
	public final void setOrder_ConfigProduct(com.mendix.systemwideinterfaces.core.IContext context, configs.proxies.ConfigProduct order_configproduct)
	{
		if (order_configproduct == null) {
			getMendixObject().setValue(context, MemberNames.Order_ConfigProduct.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Order_ConfigProduct.toString(), order_configproduct.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Order_ConfigGroup
	 */
	public final configs.proxies.ConfigGroup getOrder_ConfigGroup() throws com.mendix.core.CoreException
	{
		return getOrder_ConfigGroup(getContext());
	}

	/**
	 * @param context
	 * @return value of Order_ConfigGroup
	 * @throws com.mendix.core.CoreException
	 */
	public final configs.proxies.ConfigGroup getOrder_ConfigGroup(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		configs.proxies.ConfigGroup result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Order_ConfigGroup.toString());
		if (identifier != null) {
			result = configs.proxies.ConfigGroup.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Order_ConfigGroup
	 * @param order_configgroup
	 */
	public final void setOrder_ConfigGroup(configs.proxies.ConfigGroup order_configgroup)
	{
		setOrder_ConfigGroup(getContext(), order_configgroup);
	}

	/**
	 * Set value of Order_ConfigGroup
	 * @param context
	 * @param order_configgroup
	 */
	public final void setOrder_ConfigGroup(com.mendix.systemwideinterfaces.core.IContext context, configs.proxies.ConfigGroup order_configgroup)
	{
		if (order_configgroup == null) {
			getMendixObject().setValue(context, MemberNames.Order_ConfigGroup.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Order_ConfigGroup.toString(), order_configgroup.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Order_ConfigVariant
	 */
	public final configs.proxies.ConfigVariant getOrder_ConfigVariant() throws com.mendix.core.CoreException
	{
		return getOrder_ConfigVariant(getContext());
	}

	/**
	 * @param context
	 * @return value of Order_ConfigVariant
	 * @throws com.mendix.core.CoreException
	 */
	public final configs.proxies.ConfigVariant getOrder_ConfigVariant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		configs.proxies.ConfigVariant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Order_ConfigVariant.toString());
		if (identifier != null) {
			result = configs.proxies.ConfigVariant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Order_ConfigVariant
	 * @param order_configvariant
	 */
	public final void setOrder_ConfigVariant(configs.proxies.ConfigVariant order_configvariant)
	{
		setOrder_ConfigVariant(getContext(), order_configvariant);
	}

	/**
	 * Set value of Order_ConfigVariant
	 * @param context
	 * @param order_configvariant
	 */
	public final void setOrder_ConfigVariant(com.mendix.systemwideinterfaces.core.IContext context, configs.proxies.ConfigVariant order_configvariant)
	{
		if (order_configvariant == null) {
			getMendixObject().setValue(context, MemberNames.Order_ConfigVariant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Order_ConfigVariant.toString(), order_configvariant.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Order_ExcelDoc
	 */
	public final global.proxies.ExcelDoc getOrder_ExcelDoc() throws com.mendix.core.CoreException
	{
		return getOrder_ExcelDoc(getContext());
	}

	/**
	 * @param context
	 * @return value of Order_ExcelDoc
	 * @throws com.mendix.core.CoreException
	 */
	public final global.proxies.ExcelDoc getOrder_ExcelDoc(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		global.proxies.ExcelDoc result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Order_ExcelDoc.toString());
		if (identifier != null) {
			result = global.proxies.ExcelDoc.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Order_ExcelDoc
	 * @param order_exceldoc
	 */
	public final void setOrder_ExcelDoc(global.proxies.ExcelDoc order_exceldoc)
	{
		setOrder_ExcelDoc(getContext(), order_exceldoc);
	}

	/**
	 * Set value of Order_ExcelDoc
	 * @param context
	 * @param order_exceldoc
	 */
	public final void setOrder_ExcelDoc(com.mendix.systemwideinterfaces.core.IContext context, global.proxies.ExcelDoc order_exceldoc)
	{
		if (order_exceldoc == null) {
			getMendixObject().setValue(context, MemberNames.Order_ExcelDoc.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Order_ExcelDoc.toString(), order_exceldoc.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return orderMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final order.proxies.Order that = (order.proxies.Order) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
